apiVersion: v1
kubeVersion: v1.21.4
name: charts
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- name: postgresql
  version: 10.2.1
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: metabase
  version: 0.1.0
  repository: https://www.metabase.com/helm